platform :ios, '9.0'

target 'WeChat1' do
  pod 'Masonry', '~> 1.1.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'UIColor+SKYExtension', '0.0.1'
  pod 'UIImage+SKYExtension', '~> 0.0.1'
  pod 'TTTAttributedLabel', '~> 2.0.0'
end
